var GAME_LEVELS = [
  ["                                                                               ",
  "                                                              zzzzzy            ",
  "                       o   o   o   o         o   o   o   o    zzzzzy            ",
  "                     xxxxxxxxxxxxxxx       xxxxxxxxxxxxxxx         y            ",
  "                            x       xo   ox       x                y            ",
  "                            x        x   x        x                y            ",
  "                  o        xxx                   xxx              xxx           ",
  "                  xx      xx!xx                 xx!xx            xx!xx          ",
  "           o              x!!!x                 x!!!x            x!!!x          ",
  "           xx             xx!xx                 xx!xx            xx!xx          ",
  "                           xvx                   xvx              xvx           ",
  "                                                                            xx  ",
  "  xx            xx                     x                                     x  ",
  "  x            x                      xxx                                    x  ",
  "  x           x           zzz        xxxxx       zzz                    s  o x  ",
  "  x          xx           z                        z                         x  ",
  "  x  @       x            zzzzzzzzzzzzzzzzzzzzzzzzzz             xxxxx       x  ",
  "  xxxxxxxxxxxx                                             xxxxxxxxxxxxxxxxxxx  ",
  "              x                                            x                    ",
  "              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
  "              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
  "              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    ",
  "                                                                                ",
  "                                                                                "],
  ["                                                                                                                    x",
   "                                                                                                                    x",
   "                                                                                                                    x",
   "                                                                                                                    x",
   "                                                                                                                    x",
   "                                                                                                                    x",
   "                                                                                                                    x",
   "                                                                                                                    x",
   "                                                                                                                    x",
   "                                                                                                                    x",
   "       z                                                                                                            x",
   "      zyz                                                                                                           x",
   "     zyyyz                                                                                                          x",
   "    zzyyyzz                                                                                                         x",
   "    zzyyyzz                                                                                              x          x",
   "     zzyzz           m             m             m             m             m                                      x",
   "       y      xyyyyyyxyyyyyyxyyyyyyxyyyyyyxyyyyyyxyyyyyyxyyyyyyxyyyyyyxyyyyyyxyyyyyyxyyyyyyxxxxxxxxx              x x",
   "       y    xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                x   x",
   "       y   x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    x",
   " s o   y   x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    x",
   "xxxxxyyyyyyx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x           x        x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                   xx",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                 o  x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                 x  x",
   "xxxxxxxxvxxxxxvxxxxxvxxxxxvxxxxxvxxxxxvxxxxxvxxxxxvxxxxxvxxxxxvxxxxxvxxxxxvxxxxxvxxxxxvxxxxxvxxx            x  m    x",
   "x                                                                                                          x        x",
   "x                                                                                                         x!!!!!!!!!x",
   "x                                                                                                        x!!!!!!!!!!x",
   "x  @       o       o     o     o     o    o    o     o      o       o        o      o      o            x!!!!!!!!!!!x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                              ",
   "                     xxxxxxxxxxxxxxxx                                                                         ",
   "vvvvvvvvvvvvvvvvvvv  xxxzzzxxxxxxxxxx vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv     ",
   "                     xxxzzzxxxxxxxxxx                                                                         ",
   "                     xxxxxxxxxxxxxxxx                                                                         ",
   "      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                         ",
   "      xy yy yy yy yy y x            x                                                                         ",
   "        y  y  y  y  y  xxxxxxxxxx   x                                                                         ",
   "       @y  y  y  y  y           x    x                                                                        ",
   "      xy yy yy yy yy y  o        x    x                                                                       ",
   "      xxxxxxxxxxxxxxxxxxx         x    x                                                                      ",
   "                      x  x         x    x                                                                     ",
   "                       x  x         x    x                                                                    ",
   "                        x  x o       x    x                                                                   ",
   "                         x  xx        x    x                                                                  ",
   "                         x  x         x     x                                                                 ",
   "                        x   x         x      x                                                                ",
   "                       x    x         x       x                                                               ",
   "                      x     x         x        x                                                              ",
   "      zzzzzzzzzzzzzzzzzzz   x         x         x                                                             ",
   "      zzzzzzzzzzzzzzzzzzz   x         x          x                                                            ",
   "      yy           x        x        xx           x                                                           ",
   "      yy          x         x         x            x                                                          ",
   "      yy         x          x         x             x                                                         ",
   "                x           xm        x              x                                                        ",
   "               x            xo        x               x                                                       ",
   "              x             xx        x                x                                                      ",
   "              x            x           x                x                                                     ",
   "              x           x             x                x                                                    ",
   "              x          x               x                x                                                   ",
   "              x          x               x                 x                                                  ",
   "              x          x               x                  x                                                 ",
   "               x         x               x                   x                                                ",
   "                x         x             x                     x                                               ",
   "                 x         x o   m   s x                       x                                              ",
   "                  x         xxzzzzzzzxx                         x                                             ",
   "                   x          xxzzzzxx                           x                                            ",
   "                    x          xxxxxx                             x                                           ",
   "                     x                                             x                                          ",
   "                      x                                             x                                         ",
   "                       x                                             x                                        ",
   "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
   "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
   "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
   "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
   "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
